In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import pandas as pd
import datetime
import matplotlib


sns.set_style("darkgrid")

import warnings
warnings.filterwarnings("ignore")

import os
for dirname, _, filenames in os.walk('./XGboost_archive'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./XGboost_archive\final_no_onehot.csv

In [2]:
sales_train = pd.read_csv('./XGboost_archive/final_no_onehot.csv')
sales_train

,Unnamed: 0,CURR_SIZE_OF_PRODUCT,COMMODITY_DESC,Price_per_Q,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,PRODUCT_ID,SALES_VALUE,STORE_ID,BRAND,SUB_COMMODITY_DESC
0,0,2432,228,-0.427946,4,0,-0.488174,-0.490114,-0.316005,1,1605
1,1,2432,228,-0.190631,4,0,-0.488174,-0.297540,-0.316005,1,1605
2,2,2432,228,-0.582201,4,0,-0.488174,-0.615287,-0.332087,1,1605
3,3,2432,228,0.204895,4,0,-0.488174,0.023416,-0.316005,1,1605
4,4,2432,228,0.204895,4,0,-0.488174,0.023416,-0.332087,1,1605
...,...,...,...,...,...,...,...,...,...,...,...
1399436,1399436,912,185,-0.016599,2,1,-0.232329,-0.156319,-0.290964,0,969
1399437,1399437,49,95,-0.835338,2,1,-0.226855,-0.705155,-0.290964,1,858
1399438,1399438,865,294,-0.582201,2,1,-0.221374,-0.615287,-0.290964,0,187
1399439,1399439,1149,268,-0.483320,2,1,-0.217545,-0.535048,-0.290964,0,1772
1399440,1399440,0,104,2.538498,2,1,-0.212851,1.917060,-0.290964,0,859

In [ ]:
# sales_train = sales_train.drop('DEPARTMENT', axis = 1)
# sales_train = sales_train.drop('Date', axis = 1)
# sales_train

In [3]:
sales_train.dtypes

Unnamed: 0                int64
CURR_SIZE_OF_PRODUCT      int64
COMMODITY_DESC            int64
Price_per_Q             float64
HH_COMP_DESC              int64
HOUSEHOLD_SIZE_DESC       int64
PRODUCT_ID              float64
SALES_VALUE             float64
STORE_ID                float64
BRAND                     int64
SUB_COMMODITY_DESC        int64
dtype: object

In [ ]:
# from sklearn import preprocessing
# label_encoder = preprocessing.LabelEncoder()
# sales_train['SUB_COMMODITY_DESC'] = label_encoder.fit_transform(sales_train['SUB_COMMODITY_DESC'])
# sales_train['BRAND'] = label_encoder.fit_transform(sales_train['BRAND'])
# sales_train['AGE_DESC'] = label_encoder.fit_transform(sales_train['AGE_DESC'])
# sales_train['MARITAL_STATUS_CODE'] = label_encoder.fit_transform(sales_train['MARITAL_STATUS_CODE'])
# sales_train['INCOME_DESC'] = label_encoder.fit_transform(sales_train['INCOME_DESC'])
# sales_train['HOMEOWNER_DESC'] = label_encoder.fit_transform(sales_train['HOMEOWNER_DESC'])
# sales_train['HH_COMP_DESC'] = label_encoder.fit_transform(sales_train['HH_COMP_DESC'])
# sales_train['HOUSEHOLD_SIZE_DESC'] = label_encoder.fit_transform(sales_train['HOUSEHOLD_SIZE_DESC'])
# sales_train['KID_CATEGORY_DESC'] = label_encoder.fit_transform(sales_train['KID_CATEGORY_DESC'])

In [ ]:
# sales_train.dtypes

In [ ]:
# from sklearn.feature_selection import SelectKBest
# from sklearn.feature_selection import f_regression
# selectKBest = SelectKBest(f_regression,k=9)
# feature =sales_train[sales_train.columns[sales_train.dtypessales_train = sales_train.drop(['household_key','year', 'month', 'Mon_Block_num', 'MARITAL_STATUS_CODE', 'HOMEOWNER_DESC', 'INCOME_DESC',
#         'KID_CATEGORY_DESC'],axis= 1,inplace = False) != object]]
# # feature =df[['household_key','PRODUCT_ID','STORE_ID','BRAND','Median','year','month','Mon_Block_num','']]
# bestFeature =selectKBest.fit_transform(feature,sales_train['QUANTITY'])
# feature.columns[selectKBest.get_support()]

In [ ]:
# sales_train = sales_train.drop(['household_key','year', 'month', 'Mon_Block_num', 'MARITAL_STATUS_CODE', 'HOMEOWNER_DESC', 'INCOME_DESC',
#         'KID_CATEGORY_DESC'],axis= 1,inplace = False)

In [4]:
sales_train = sales_train.drop(['Unnamed: 0'],axis= 1,inplace = False)
sales_train

,CURR_SIZE_OF_PRODUCT,COMMODITY_DESC,Price_per_Q,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,PRODUCT_ID,SALES_VALUE,STORE_ID,BRAND,SUB_COMMODITY_DESC
0,2432,228,-0.427946,4,0,-0.488174,-0.490114,-0.316005,1,1605
1,2432,228,-0.190631,4,0,-0.488174,-0.297540,-0.316005,1,1605
2,2432,228,-0.582201,4,0,-0.488174,-0.615287,-0.332087,1,1605
3,2432,228,0.204895,4,0,-0.488174,0.023416,-0.316005,1,1605
4,2432,228,0.204895,4,0,-0.488174,0.023416,-0.332087,1,1605
...,...,...,...,...,...,...,...,...,...,...
1399436,912,185,-0.016599,2,1,-0.232329,-0.156319,-0.290964,0,969
1399437,49,95,-0.835338,2,1,-0.226855,-0.705155,-0.290964,1,858
1399438,865,294,-0.582201,2,1,-0.221374,-0.615287,-0.290964,0,187
1399439,1149,268,-0.483320,2,1,-0.217545,-0.535048,-0.290964,0,1772
1399440,0,104,2.538498,2,1,-0.212851,1.917060,-0.290964,0,859

In [5]:
sales_train['CURR_SIZE_OF_PRODUCT'] = sales_train['CURR_SIZE_OF_PRODUCT'].astype('object')
sales_train['COMMODITY_DESC'] = sales_train['COMMODITY_DESC'].astype('object')
sales_train['HH_COMP_DESC'] = sales_train['HH_COMP_DESC'].astype('object')
sales_train['HOUSEHOLD_SIZE_DESC'] = sales_train['HOUSEHOLD_SIZE_DESC'].astype('object')
sales_train['BRAND'] = sales_train['BRAND'].astype('object')
sales_train['SUB_COMMODITY_DESC'] = sales_train['SUB_COMMODITY_DESC'].astype('object')

In [6]:
sales_train2 = pd.get_dummies(sales_train)

In [ ]:
# sales_train2[sales_train2.columns[sales_train2.dtypes==object]]

In [ ]:
# sales_train2 = preprocessing.normalize(sales_train2)

In [7]:
sales_train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1399441 entries, 0 to 1399440
Columns: 6196 entries, Price_per_Q to SUB_COMMODITY_DESC_2265
dtypes: float64(4), uint8(6192)
memory usage: 8.1 GB

In [8]:
sales_train2.shape

(1399441, 6196)

In [11]:
sales_train2

,Price_per_Q,PRODUCT_ID,SALES_VALUE,STORE_ID,CURR_SIZE_OF_PRODUCT_0,CURR_SIZE_OF_PRODUCT_1,CURR_SIZE_OF_PRODUCT_2,CURR_SIZE_OF_PRODUCT_3,CURR_SIZE_OF_PRODUCT_4,CURR_SIZE_OF_PRODUCT_5,...,SUB_COMMODITY_DESC_2256,SUB_COMMODITY_DESC_2257,SUB_COMMODITY_DESC_2258,SUB_COMMODITY_DESC_2259,SUB_COMMODITY_DESC_2260,SUB_COMMODITY_DESC_2261,SUB_COMMODITY_DESC_2262,SUB_COMMODITY_DESC_2263,SUB_COMMODITY_DESC_2264,SUB_COMMODITY_DESC_2265
0,-0.427946,-0.488174,-0.490114,-0.316005,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,-0.190631,-0.488174,-0.297540,-0.316005,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-0.582201,-0.488174,-0.615287,-0.332087,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.204895,-0.488174,0.023416,-0.316005,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.204895,-0.488174,0.023416,-0.332087,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399436,-0.016599,-0.232329,-0.156319,-0.290964,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399437,-0.835338,-0.226855,-0.705155,-0.290964,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399438,-0.582201,-0.221374,-0.615287,-0.290964,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399439,-0.483320,-0.217545,-0.535048,-0.290964,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399440,2.538498,-0.212851,1.917060,-0.290964,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

# #one hot encoding categorical data for modelling
# encoded = pd.get_dummies(data[data.columns[data.dtypes==object]])
# data_encoded = pd.concat([encoded, data[data.columns[data.dtypes != object]]],axis=1)

#Features (X) and the target (y)
X = sales_train2.drop("QUANTITY",axis=1)
y = sales_train2.QUANTITY

#lets start with the default hyperparameters and hold-out mechanism for train/test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
#XGBoost
xgb_mdl = XGBClassifier().fit(X_train.values,y_train.values)
xgb_mdl

KeyError: "['QUANTITY'] not found in axis"